/**
 * マークダウン入力ヘルパーの種類。
 */
const MARKDOWN = {
  HELPER: {
    LINK: 'LINK',
    IMAGE_LARGE: 'IMAGE_LARGE',
    IMAGE_MEDIUM: 'IMAGE_MEDIUM',
    IMAGE_SMALL: 'IMAGE_SMALL',
    HEADER_1: 'HEADER_1',
    HEADER_2: 'HEADER_2',
    HEADER_3: 'HEADER_3',
    STRIKETHROUGH: 'STRIKETHROUGH',
    EMPHASIS: 'EMPHASIS',
    ITALIC: 'ITALIC',
    QUOTE: 'QUOTE',
    UNORDERED_LIST: 'UNORDERED_LIST',
    ORDERED_LIST: 'ORDERED_LIST',
  },
}

export default MARKDOWN
